### ISSUE TITLE
When to round

### ISSUE THREAD

**Issue by J-R-Mann** [sdanielzafar/NAVtrackr#7]
Add feature that allows rounding either pre or post splitting. Right now time is rounded, then split. I would like to split and then round. This makes it so you don't end up with goofy decimals for a task. e.g. one task with three time codes billed for an hour will end up at .33, .33, .33. Maybe that should be rounded to the nearest 0.05 or 3 minute increment.

**Comment by sdanielzafar** [comment]
I feel there is a lot to do with regard to rounding. pre-post split rounding is important, but also functionality should be added to round evenly instead of only down. I see this as being two separate arguments. Any other ideas here?

**Comment by sdanielzafar** [comment]
from Knud:

Dan,

At some point (i.e., pretty low priority) could you have NAVTracker do it’s rounding after it splits projects between multiple activity codes? I like to round my time to the nearest tenth of an hour (6 min) but for projects where I split my time between two activity codes this still leads to digits in the hundredths place.

**Comment by sdanielzafar** [comment]
I moved the rounding to occur at the end of the toggl pull and wrangle, should fix this
